[package]
name = "processor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
isa = { path = "../isa" }
env_logger = "0.10.1"
log = "0.4.20"
async-channel = "2.1.1"
