pub trait InstructionDisplay {
    fn display(&self) -> String;
}

impl InstructionDisplay for isa::Instruction {
    fn display(&self) -> String {
        match self {
            isa::Instruction::InvalidInstruction => todo!(),
            isa::Instruction::LOAD => todo!(),
            isa::Instruction::LOADN => todo!(),
            isa::Instruction::LOADI => todo!(),
            isa::Instruction::STORE => todo!(),
            isa::Instruction::STOREN => todo!(),
            isa::Instruction::STOREI => todo!(),
            isa::Instruction::MOV => todo!(),
            isa::Instruction::INPUT => todo!(),
            isa::Instruction::OUTPUT => todo!(),
            isa::Instruction::OUTCHAR => todo!(),
            isa::Instruction::INCHAR => todo!(),
            isa::Instruction::SOUND => todo!(),
            isa::Instruction::ADD => todo!(),
            isa::Instruction::ADDC => todo!(),
            isa::Instruction::SUB => todo!(),
            isa::Instruction::SUBC => todo!(),
            isa::Instruction::MUL => todo!(),
            isa::Instruction::DIV => todo!(),
            isa::Instruction::INC => todo!(),
            isa::Instruction::DEC => todo!(),
            isa::Instruction::MOD => todo!(),
            isa::Instruction::AND => todo!(),
            isa::Instruction::OR => todo!(),
            isa::Instruction::XOR => todo!(),
            isa::Instruction::NOT => todo!(),
            isa::Instruction::SHIFTL0 => todo!(),
            isa::Instruction::SHIFTL1 => todo!(),
            isa::Instruction::SHIFTR0 => todo!(),
            isa::Instruction::SHIFTR1 => todo!(),
            isa::Instruction::ROTL => todo!(),
            isa::Instruction::ROTR => todo!(),
            isa::Instruction::CMP => todo!(),
            isa::Instruction::JMP => todo!(),
            isa::Instruction::JEQ => todo!(),
            isa::Instruction::JNE => todo!(),
            isa::Instruction::JZ => todo!(),
            isa::Instruction::JNZ => todo!(),
            isa::Instruction::JC => todo!(),
            isa::Instruction::JNC => todo!(),
            isa::Instruction::JGR => todo!(),
            isa::Instruction::JLE => todo!(),
            isa::Instruction::JEG => todo!(),
            isa::Instruction::JEL => todo!(),
            isa::Instruction::JOV => todo!(),
            isa::Instruction::JNO => todo!(),
            isa::Instruction::JDZ => todo!(),
            isa::Instruction::JN => todo!(),
            isa::Instruction::CALL => todo!(),
            isa::Instruction::CEQ => todo!(),
            isa::Instruction::CNE => todo!(),
            isa::Instruction::CZ => todo!(),
            isa::Instruction::CNZ => todo!(),
            isa::Instruction::CC => todo!(),
            isa::Instruction::CNC => todo!(),
            isa::Instruction::CGR => todo!(),
            isa::Instruction::CLE => todo!(),
            isa::Instruction::CEG => todo!(),
            isa::Instruction::CEL => todo!(),
            isa::Instruction::COV => todo!(),
            isa::Instruction::CNO => todo!(),
            isa::Instruction::CDZ => todo!(),
            isa::Instruction::CN => todo!(),
            isa::Instruction::RTS => todo!(),
            isa::Instruction::RTI => todo!(),
            isa::Instruction::PUSH => todo!(),
            isa::Instruction::POP => todo!(),
            isa::Instruction::NOP => todo!(),
            isa::Instruction::HALT => todo!(),
            isa::Instruction::CLEARC => todo!(),
            isa::Instruction::SETC => todo!(),
            isa::Instruction::BREAKP => todo!(),
        }
    }
}
